update meta-openembedded
This fixes build issue due to ZIP not allowing dates before 1980:
  ValueError: ZIP does not support timestamps before 1980

The issue has been introduced with the recent update of meta-
updater, which enabled reproducible builds and file timestamps
of Unix time 0.

Signed-off-by: Stefan Agner <stefan.agner@toradex.com>